// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"go-geektime/internal/user/biz"
	"go-geektime/internal/user/data"
	"go-geektime/internal/user/server"
	"go-geektime/internal/user/service"
	"google.golang.org/grpc"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func depend() (*grpc.Server, func(), error) {
	userData, cleanup, err := data.NewUserData()
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(userData)
	userBiz, cleanup2, err := biz.NewUserBiz(userRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userService, cleanup3, err := service.NewUserService(userBiz)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	grpcServer, cleanup4, err := server.NewUserGPRCServer(userService)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return grpcServer, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
